### ISSUE TITLE
Crash when use "Heap Objects" In some apps

### ISSUE THREAD

**Issue by nonstriater** [qiaoxueshi/FLEXLoader#7] opened 2016-04-03 08:04 UTC
It crashed when i use "Heap Objects" feature in Flex which install by FlexLoader, but it work well when i directly install it with its source code in my project. crash info:

```
Incident Identifier: 517586F3-6879-4EAB-A35E-1EE39320B29B
CrashReporter Key:   aef632fc24f9f7ca54b83473a58531929617bd97
Hardware Model:      iPod7,1
Process:             OneTravel [5084]
Path:                /private/var/mobile/Containers/Bundle/Application/34675BD3-2474-42E7-876E-48557AF16E6A/OneTravel.app/OneTravel
Identifier:          com.xiaojukeji.didi.rwj
Version:             4.3.0.201603301705 (4.3.0)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2016-04-03 17:26:52.318 +0800
Launch Time:         2016-04-03 17:26:46.962 +0800
OS Version:          iOS 8.4 (12H143)
Report Version:      105

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   ???                             000000000000000000 0 + 0
1   FLEXDylib.dylib                 0x0000000106ad0300 0x106aa4000 + 180992
2   FLEXDylib.dylib                 0x0000000106ada430 0x106aa4000 + 222256
3   FLEXDylib.dylib                 0x0000000106ada2f4 0x106aa4000 + 221940
4   UIKit                           0x00000001899d8c18 -[UIViewController loadViewIfRequired] + 692
5   UIKit                           0x00000001899d8928 -[UIViewController view] + 32
6   UIKit                           0x0000000189b7b1f0 -[UINavigationController _startCustomTransition:] + 712
7   UIKit                           0x0000000189a8de84 -[UINavigationController _startDeferredTransitionIfNeeded:] + 468
8   UIKit                           0x0000000189a8dc50 -[UINavigationController __viewWillLayoutSubviews] + 56
9   UIKit                           0x0000000189a8dbd0 -[UILayoutContainerView layoutSubviews] + 200
10  UIKit                           0x00000001899d56f4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 580
11  QuartzCore                      0x0000000189311db8 -[CALayer layoutSublayers] + 152
12  QuartzCore                      0x000000018930c820 CA::Layer::layout_if_needed(CA::Transaction*) + 320
13  QuartzCore                      0x000000018930c6c4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
14  QuartzCore                      0x000000018930be58 CA::Context::commit_transaction(CA::Transaction*) + 276
15  QuartzCore                      0x000000018930bbd8 CA::Transaction::commit() + 528
16  QuartzCore                      0x0000000189305300 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80
17  CoreFoundation                  0x0000000184f182a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
18  CoreFoundation                  0x0000000184f15230 __CFRunLoopDoObservers + 360
19  CoreFoundation                  0x0000000184f15610 __CFRunLoopRun + 836
20  CoreFoundation                  0x0000000184e412d4 CFRunLoopRunSpecific + 396
21  GraphicsServices                0x000000018e73f6fc GSEventRunModal + 168
22  UIKit                           0x0000000189a3ef40 UIApplicationMain + 1488
23  OneTravel                       0x00000001000e63dc main (main.m:14)
24  libdyld.dylib                   0x0000000196a56a08 start + 4
25  ???                             000000000000000000 0 + 0
```

**Comment by qiaoxueshi** [comment] 2017-03-21 15:16
The issue is too early, sorry to close it.

**Closed by qiaoxueshi** 2017-03-21 15:16 UTC
